In [1]:
a = 1
print a

1


In [2]:
a = 1.76
print a, type(a)
a = 'foo'
print a, type(a)

1.76 <type 'float'>
foo <type 'str'>


In [3]:
my_list = [1, 2, 3, 'bar', None]
print my_list

[1, 2, 3, 'bar', None]


In [4]:
my_list[2] = 42
print my_list
my_list += [4, [7, 8, 0.3], []]
print my_list

[1, 2, 42, 'bar', None]
[1, 2, 42, 'bar', None, 4, [7, 8, 0.3], []]


In [5]:
my_tuple = ('hello', 5, 'world')
print my_tuple

('hello', 5, 'world')


In [6]:
my_tuple[0] = 'goodbye' # not allowed!

TypeError: 'tuple' object does not support item assignment

In [7]:
my_dict = {'a': 1, 'b': [5, 6], 'c': 'foo'}
print my_dict
print my_dict['b']
print my_dict.keys()
print 'hashmap'

{'a': 1, 'c': 'foo', 'b': [5, 6]}
[5, 6]
['a', 'c', 'b']
hashmap


In [8]:
my_dict[23] = 'c'
print my_dict

{'a': 1, 'c': 'foo', 'b': [5, 6], 23: 'c'}


In [9]:
if my_dict[23] == '4':
    print 'yay'
elif 'b' in my_dict.keys():
    print 'got it!'
else:
    print 'wat?'
    

got it!


In [10]:
for i in [10, 11, 12]:
    print i ** 2
    

100
121
144


In [11]:
for i in range(5):
    print i

0
1
2
3
4


In [12]:
i = 10
while i < 13:
    print "There's no such month as 'Rocktober'"
    i += 1
    

There's no such month as 'Rocktober'
There's no such month as 'Rocktober'
There's no such month as 'Rocktober'


In [13]:
def double(x):
    return x * 2

print double('abc')


abcabc


In [14]:
print [1, 2, 3] + [4, 3]  # remember the concatenation operator '+'?


[1, 2, 3, 4, 3]


In [15]:
print double([1, 2, 3])


[1, 2, 3, 1, 2, 3]


In [16]:
def my_func(a, b):
    x = a * b
    if x > 0:
        for i in range(x):
            y = x * x
            print y
            
        print "done"        
    else:
        print "error"
        
    return x


In [17]:
my_func(1, 2)

4
4
done


2

In [18]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [19]:
a = ones(())  # the empty tuple () means that there are no dimensions at all
print a
print a.shape  # the shape field holds the shape tuple, in this case it is empty, indicating the lack of dimensions

1.0
()


In [20]:
b = ones((2,))  # we pass a tuple with a single element, meaning we want a single dimension of length 2
print b
print b.shape

[ 1.  1.]
(2,)


In [21]:
print b.T  #transpose
print b.T.shape

[ 1.  1.]
(2,)


In [22]:
c = ones((3, 2))
print c
print c.shape

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
(3, 2)


In [23]:
d = ones((4, 3, 2))
print d
print d.shape

[[[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]]
(4, 3, 2)


In [24]:
x = array([[1., 2.], 
           [3., 4.]])

In [25]:
print x[0, 1]

2.0


In [26]:
C = eye(10) # creates a 2d matrix with ones on the diagonal and zeros elsewhere
print C

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [27]:
print C[:, 3], '\n'       # all the rows of column with index 3. Note how the result becomes a row vector!
print C[4:7, :], '\n'     # all the columns of rows 4, 5 and 6
print C[4:7, 4:8], '\n'   # columns 4, 5, 6, 7 of rows 4, 5 and 6

[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.] 

[[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]] 



In [28]:
print C[:, [1, 3, 5]]   # all the rows of columns 1, 3 and 5

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [29]:
a = array([[1., 0.], 
           [0.5, 2.3]])

b = array([[0.5, 1.0], 
           [1.0, 0.8]])

print a * b, '\n'
print 'as a. * b in matlab'

[[ 0.5   0.  ]
 [ 0.5   1.84]] 

as a. * b in matlab


In [30]:
print a * ones((3,2))

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [31]:
c = array([0.5, 1.0])
print a * c
print 'as a.*[c;c] in matlab'

[[ 0.5   0.  ]
 [ 0.25  2.3 ]]
as a.*[c;c] in matlab


In [32]:
print a.shape, c.shape

(2, 2) (2,)


In [33]:
c_ext = array([[0.5, 1.0],
               [0.5, 1.0]])

print c, '\n'
print c_ext

[ 0.5  1. ] 

[[ 0.5  1. ]
 [ 0.5  1. ]]


In [35]:
print a * c
print a * c_ext
print 'as a.*[c\' c\'] in matlab'

[[ 0.5   0.  ]
 [ 0.25  2.3 ]]
[[ 0.5   0.  ]
 [ 0.25  2.3 ]]
as a.*[c' c'] in matlab


In [36]:
c_ext_cols = array([[0.5, 0.5],
                    [1.0, 1.0]])

print a * c_ext_cols

[[ 0.5  0. ]
 [ 0.5  2.3]]


In [37]:
print c[:, newaxis].shape
print a * c[:, newaxis]

(2, 1)
[[ 0.5  0. ]
 [ 0.5  2.3]]


In [38]:
print a[:, newaxis, :].shape
print c[newaxis, :, newaxis].shape

(2, 1, 2)
(1, 2, 1)


In [42]:
print a, '\n'
print c, '\n'
print a[:, newaxis, :] * c[newaxis, :, newaxis]
print '\n'
print 'two lines in matlab:'
print 'g(:,:,1)=(a(1,:)\'*c)\';'
print 'g(:,:,2)=(a(2,:)\'*c)\';'

[[ 1.   0. ]
 [ 0.5  2.3]] 

[ 0.5  1. ] 

[[[ 0.5   0.  ]
  [ 1.    0.  ]]

 [[ 0.25  1.15]
  [ 0.5   2.3 ]]]


two lines in matlab:
g(:,:,1)=(a(1,:)'*c)';
g(:,:,2)=(a(2,:)'*c)';


In [43]:
FCD = array([[[ 0.272,  0.34 ,  0.068],
              [ 0.017,  0.034,  0.119]],

             [[ 0.048,  0.06 ,  0.012],
              [ 0.003,  0.006,  0.021]]])

In [60]:
CD = FCD.sum(0)  # sums out the 0th axis (F). Equivalent to FCD.sum(axis=0)
print 'matlab: CD = sum(CDF,3), because the axis 0 is represented as z in matlab, ergo 3'
print CD.shape
print CD
C = CD.sum(1)
print 'matlab: C = sum(CD,2), because the axis 1 is represented as y in matlab, ergo 2'
print C

matlab: CD = sum(CDF,3), because the axis 0 is represented as z in matlab, ergo 3
(2, 3)
[[ 0.32  0.4   0.08]
 [ 0.02  0.04  0.14]]
matlab: C = sum(CD,2), because the axis 1 is represented as y in matlab, ergo 2
[ 0.8  0.2]


In [45]:
print FCD.sum()

1.0


In [58]:
FC = FCD.sum(2)
print FC
print 'matlab: FC = sum(FCD,2)'
print 'matlab: FC = (squeeze(FC))\''
print '\n'
F_cond_C = FC / C  # C gets broadcasted over all rows!
print F_cond_C
print 'matlab: F_cond_C = [FC / C\'  FC / C\']'

[[ 0.68  0.17]
 [ 0.12  0.03]]
matlab: FC = sum(FCD,2)
matlab: FC = (squeeze(FC))'


[[ 0.85  0.85]
 [ 0.15  0.15]]
matlab: F_cond_C = [FC / C'  FC / C']


In [59]:
print F_cond_C[:, 1]
print 'matlab: F_cond_C = FC / C\''

[ 0.85  0.15]
matlab: F_cond_C = FC / C'


In [49]:
print FCD
print FCD.shape

[[[ 0.272  0.34   0.068]
  [ 0.017  0.034  0.119]]

 [[ 0.048  0.06   0.012]
  [ 0.003  0.006  0.021]]]
(2, 2, 3)
