In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
## First exercise

In [3]:
# L = Cold, H = Hungry, Y = Crying

In [79]:
YHL = array([[[0.075, 0.045],
              [0.023, 0.007]],
             
             [[0.08, 0.17],
              [0.17, 0.43]]])

In [80]:
print YHL

[[[ 0.075  0.045]
  [ 0.023  0.007]]

 [[ 0.08   0.17 ]
  [ 0.17   0.43 ]]]


In [116]:
# Summing over the crying axis
YH = YHL.sum(2)  # marginalising L & H
Y = YH.sum(1)
print Y[0]
print 'there is 15% probability that Olivia is crying'

0.15
there is 15% probability that Olivia is crying


In [128]:
#HY = YHL.sum(2)
H_cond_Y = YH / Y [0]
print H_cond_Y[0,0]
print 'there is 80% probability that Olivia is hungry when she is crying'

0.8
there is 80% probability that Olivia is hungry when she is crying


In [127]:
YL = YHL.sum(1)
L = YL.sum(0)
Y_cond_L = YL / L [0]
print L
print Y_cond_L[0,0]
print 'there is 28% probability that Olivia is crying when she is cold'

[ 0.348  0.652]
0.281609195402
there is 28% probability that Olivia is crying when she is cold


In [126]:
H = YH.sum(0)
print H
print '\n'
print 'P(Y,h)'
print YHL[:,0,:]
print '\n'
print 'P(Y|h)'
print YHL[:,0,:]/H[0]

[ 0.37  0.63]


P(Y,h)
[[ 0.075  0.045]
 [ 0.08   0.17 ]]


P(Y|h)
[[ 0.2027027   0.12162162]
 [ 0.21621622  0.45945946]]


In [129]:
## Second exercise

In [144]:
# G = Gender, W = glass Wearer
GW = array ([[0.65, 0.35],
             [0.55, 0.45]])
P = 0.01
print GW
#print GW[1,0]

[[ 0.65  0.35]
 [ 0.55  0.45]]


In [146]:
W = GW.sum(0)
W_cond = W / W.sum(0)
print W_cond[0]
W_P = W_cond[0] * P
print W_P
print 'there is 0.6% probability that the first person he meets is a glass wearer with a pink car'

0.6
0.006
there is 0.6% probability that the first person he meets is a glass wearer with a pink car


In [148]:
GW_P = GW[0,0] * P
print GW_P
print 'there is 0.65% probability that the first man he meets is a glass wearer with a pink car'

0.0065
there is 0.65% probability that the first man he meets is a glass wearer with a pink car


In [149]:
print W

[ 1.2  0.8]


In [153]:
G_cond_W = GW[:,0] / W[0]
print G_cond_W
print GW_P
print 'there is 54% that the killer is a man, 46% that is a woman'

[ 0.54166667  0.45833333]
0.0065
there is 54% that the killer is a man, 46% that is a woman


In [154]:
## Third exercise

In [185]:
FC = array ([[3.0, 0.0, 2.0],
            [4.0,  2.0, 1.0],
            [1.0,  3.0, 0.0]])
FC_tot = FC / FC.sum(1).sum(0)
B = array([0.3, 0.2, 0.5])
#FC_col = FC
for i in range(3):
    FC_col[:,i] = FC[:,i] / FC[:,i].sum(0)

print 'probability of fruits and colours'
print FC_tot
print '\n'
print 'probability of the boxes'
print B
print '\n'
print 'probability by column'
print FC_col 

probability of fruits and colours
[[ 0.1875  0.      0.125 ]
 [ 0.25    0.125   0.0625]
 [ 0.0625  0.1875  0.    ]]


probability of the boxes
[ 0.3  0.2  0.5]


probability by column
[[ 0.375       0.          0.66666667]
 [ 0.5         0.4         0.33333333]
 [ 0.125       0.6         0.        ]]


In [193]:
o = (FC_col[1,:] * B).sum(0) # P(o)
print 'probability of selecting an orange, if a box is chosen at random with probabilities' 
print ' P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box ' 
print '(with equal probability of selecting any of the items in the box)'
print o

probability of selecting an orange, if a box is chosen at random with probabilities
 P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box 
(with equal probability of selecting any of the items in the box)
0.396666666667


In [198]:
# P(a) P(g|a) = P(a|g) * P(g) / P(a) = (P(a,g) * P(g) / P(g) ) / P(a) = P(a,g) / P(a)
a = (FC_col[0,:] * B).sum(0) # P(a)
print 'probability of selecting an apple, if a box is chosen at random with probabilities' 
print ' P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box ' 
print '(with equal probability of selecting any of the items in the box)'
print a

probability of selecting an apple, if a box is chosen at random with probabilities
 P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box 
(with equal probability of selecting any of the items in the box)
0.445833333333


In [204]:
print 'If we observe that the selected fruit is in fact an apple, what is the probability that it'
print 'came from the green box? Assume, that we chose the box with the same probabilities'
print 'as in question 1.3B. Hint: Use Bayes’ rule.'
ga = FC_col[0,2] * B[2] / a
print ga

If we observe that the selected fruit is in fact an apple, what is the probability that it
came from the green box? Assume, that we chose the box with the same probabilities
as in question 1.3B. Hint: Use Bayes’ rule.
0.747663551402


In [ ]:
## Fouth exercise
# A) False
# B) False
# C) False
# D) True
# E) True
# F) False
# G) True
# H) True