In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


First exercise
========

In [16]:
# L = Cold, H = Hungry, Y = Crying
print 'L = Cold, H = Hungry, Y = Crying'

L = Cold, H = Hungry, Y = Crying


In [4]:
YHL = array([[[0.075, 0.045],
              [0.023, 0.007]],
             
             [[0.08, 0.17],
              [0.17, 0.43]]])

In [17]:
# Summing over the crying axis
YH = YHL.sum(2)  # marginalising L & H
Y = YH.sum(1)
print '1A) At some random night-time, there is ' + `round(Y[0],2)*100` + '% probability that Olivia is crying.'

1A) At some random night-time, there is 15.0% probability that Olivia is crying.


In [29]:
H_cond_Y = YH / Y [0]
print 'What is the probability that Olivia is hungry when she is crying?'
print 'P(h|y) = P(h^y) / P(y)'
print '1B) There is ' + `round(H_cond_Y[0,0],2)*100` + '% probability that Olivia is hungry when she is crying.'

What is the probability that Olivia is hungry when she is crying?
P(h|y) = P(h^y) / P(y)
1B) There is 80.0% probability that Olivia is hungry when she is crying.


In [31]:
YL = YHL.sum(1)
L = YL.sum(0)
Y_cond_L = YL / L [0]
print 'What is the probability that Olivia is crying when she is cold? '
print 'P(y|l) = P(y^l) / P(l)'
print '1C) there is ' + `round(Y_cond_L[0,0],2)*1000/10` + '% probability that Olivia is crying when she is cold'

What is the probability that Olivia is crying when she is cold? 
P(y|l) = P(y^l) / P(l)
1C) there is 28.0% probability that Olivia is crying when she is cold


In [89]:
H = YH.sum(0)
print '1D) Compute P(Crying, hungry) and P(Crying | hungry) (mind the lowercase “hungry”).'
print 'P(Y,h)'
YhL = YHL[:,0,:]
Yh = YhL.sum(1)
print Yh
print 'P(Crying, hungry) represents the probability of conjunctions (joint event) of the hungry events with any Crying event.'
print '\n'
print 'P(Y|h)'
print Yh/H[0]
print 'P(Crying|hungry) represents the probability of conditional distribution of the hungry events with any Crying event.'

1D) Compute P(Crying, hungry) and P(Crying | hungry) (mind the lowercase “hungry”).
P(Y,h)
[ 0.12  0.25]
P(Crying, hungry) represents the probability of conjunctions (joint event) of the hungry events with any Crying event.


P(Y|h)
[ 0.32432432  0.67567568]
P(Crying|hungry) represents the probability of conditional distribution of the hungry events with any Crying event.


Second exercise
========

In [88]:
# G = Gender, W = glass Wearer
GW = array ([[0.65, 0.35],
             [0.55, 0.45]])
p = 0.01 # probability of having a pink car
m = 0.50 # probability of being a man

In [71]:
W = GW.sum(0)
W_cond = W / W.sum(0)
#print W_cond[0]
wp = W_cond[0] * p
print '2A) There is ' + `round(wp,3)*100` + '% probability that the first person he meets is a glass wearer with a pink car, G(w ^ p).'

2A) There is 0.6% probability that the first person he meets is a glass wearer with a pink car, G(w ^ p).


In [86]:
mwp = GW[1,0] * P
mwp_cond_m = GW_P / m
print '2B) There is ' + `round(mwp_cond_m,4)*1000/10` + '% probability that the first man he meets is a glass wearer with a pink car, P(m ^ w ^ p | m).'

2B) There is 1.1% probability that the first man he meets is a glass wearer with a pink car, P(m ^ w ^ p | m).


In [87]:
G_cond_W = GW[:,0] / W[0]
print G_cond_W
print '2C) there is 54% that the killer is a man, 46% that is a woman, P(G| w).'

[ 0.54166667  0.45833333]
2C) there is 54% that the killer is a man, 46% that is a woman, P(G| w).


Third exercise
========

In [97]:
FC = array ([[3.0, 0.0, 2.0],
            [4.0,  2.0, 1.0],
            [1.0,  3.0, 0.0]])
FC_tot = FC / FC.sum(1).sum(0)
B = array([0.3, 0.2, 0.5])
FC_col = FC
for i in range(3):
    FC_col[:,i] = FC[:,i] / FC[:,i].sum(0)

print 'probability of fruits and colours'
print FC_tot
print '\n'
print 'probability of the boxes'
print B
print '\n'
print '3A) Probability given the colour of the boxes:'
print FC_col 

probability of fruits and colours
[[ 0.1875  0.      0.125 ]
 [ 0.25    0.125   0.0625]
 [ 0.0625  0.1875  0.    ]]


probability of the boxes
[ 0.3  0.2  0.5]


3A) Probability given the colour of the boxes:
[[ 0.375       0.          0.66666667]
 [ 0.5         0.4         0.33333333]
 [ 0.125       0.6         0.        ]]


In [106]:
o = (FC_col[1,:] * B).sum(0)
print '3B) Probability of selecting an orange, if a box is chosen at random with probabilities' 
print ' P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box ' 
print '(with equal probability of selecting any of the items in the box) is ' + `round(o,2)*100` + '% = P(o).'

3B) Probability of selecting an orange, if a box is chosen at random with probabilities
 P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box 
(with equal probability of selecting any of the items in the box) is 40.0% = P(o).


In [107]:
a = (FC_col[0,:] * B).sum(0) # P(a)
print 'Probability of selecting an apple, if a box is chosen at random with probabilities' 
print ' P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box ' 
print '(with equal probability of selecting any of the items in the box) is ' + `round(a,2)*100` + '%.'

Probability of selecting an apple, if a box is chosen at random with probabilities
 P(r) = 0.3, P(b) = 0.2, P(g) = 0.5, and one piece of fruit is chosen randomly from this box 
(with equal probability of selecting any of the items in the box) is 45.0%.


In [109]:
print 'P(g|a) = P(a|g) * P(g) / P(a) = (P(a,g) * P(g) / P(g) ) / P(a) = P(a,g) / P(a)'
g_cond_a = FC_col[0,2] * B[2] / a
print '3C) If we observe that the selected fruit is in fact an apple, what is the probability that it'
print 'came from the green box? If we assume, that we chose the box with the same probabilities'
print 'as in question 1.3B, the answer is ' + `round(g_cond_a,2)*100` + '%.'

P(g|a) = P(a|g) * P(g) / P(a) = (P(a,g) * P(g) / P(g) ) / P(a) = P(a,g) / P(a)
3C) If we observe that the selected fruit is in fact an apple, what is the probability that it
came from the green box? If we assume, that we chose the box with the same probabilities
as in question 1.3B, the answer is 75.0%.


Fourth exercise
==========

### A) BA┴BP is false.
BP is casually correlated to BA.

### B) CH┴BS is true.
Since BP is not given, and CH and BS do not share parents, they are marginally indipendent.

### C) CS┴LW is false.
They share BP as parent (of second level for CS), thus they are not marginally indipendent.

### D) BA┴BP|BS is true.
Given BS, any information provided by BA is redundant to know the probability distribution of BP. Thus, BA is conditionally indipendent from BP, given BS.

### E) CH ┴ BA | BP is false.
Knowing BA and BP is a sufficient condition to determine the probability distribution of CH. Thus, CH is not conditionally indipendent from BA, given BP.

### F) CS ┴ LW | CH is false.
CS and LW share BP as parent, condition that is not influenced by their conditional probability given CH.

### G) BS ┴ LW | BP is true.
Given BP, any information provided by BS is redundant to know the probability distribution of LW. 

### H) CH ┴ BA | BP, BS is false.
Same as E). Knowing even BS, it makes only easier to calculate the probability distribution of CH, given its child BP.