In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


This Jupyter notebook shows you some commands you might find useful for Assignment 2. You still have to use them properly :)

If you want help for a specific command, just type the command in a code cell with a ? at the end and press ENTER. This will open the documentation of the command.

In [2]:
searchsorted?


The following commands might be useful for sampling...

In [4]:
x = array([3., 5., 10.])
print x.cumsum()
print x.searchsorted(4)
print x.searchsorted([2, 4, 9, 13])
print random.sample(10)

[  3.   8.  18.]
1
[0 1 2 3]
[ 0.2051235   0.12534328  0.3378913   0.94646307  0.95350665  0.09435915
  0.06262741  0.63154342  0.52426105  0.20888211]


You can use binary masks for indexing in an array:

In [5]:
x = random.sample(10)
print x > 0.5
print x[x > 0.5]
# & .. and     | .. or     ~ .. not     ^ .. xor
print x[(x > 0.5) & (x < 0.8)]

[ True  True False  True  True  True False False  True False]
[ 0.91584197  0.86234061  0.53197373  0.70585477  0.89772089  0.94118858]
[ 0.53197373  0.70585477]


You can use the `.transpose(...)` method to shuffle dimensions:

In [6]:
# create a random conditional probability distribution P(A | B, C, D)
A_BCD = random.sample((2, 3, 4, 5))
A_BCD /= A_BCD.sum(axis=0)[newaxis, :, :, :]

# create a random joint probability distribution P(C, D, B)
CDB = random.sample((4, 5, 3))
CDB /= CDB.sum()

# now we compute the full joint P(A, B, C, D)
#ABCD = A_BCD * CDB[newaxis, :, :, :]  # ERROR: wrong alignment. 
ABCD = A_BCD * CDB.transpose(2, 0, 1)[newaxis, :, :, :]
print ABCD.sum()

1.0


The `.transpose(...)` command 'reorders' the dimensions according to the given parameters. In our case, we wanted dimension 2 (B) to be first, then dimension 0 (C), then dimension 1 (D), in order to get `BCD`. *We advice you to name your variables in a way that reflects which variable corresponds to which dimension to avoid confusion!*

By the way, `.T` is a shortcut for the following transpose command:

In [6]:
print (ABCD.T == ABCD.transpose(3, 2, 1, 0)).all()

True


This might be more intuitive with two dimensions:

In [7]:
x = random.sample((3, 3))
print x
print (x.T == x.transpose(1, 0)).all()

[[ 0.95364823  0.92125739  0.41517168]
 [ 0.56783634  0.22244431  0.0378399 ]
 [ 0.8860816   0.25215939  0.24096788]]
True


In [11]:
def printme(a):
   "This prints a passed string into this function"
   #print str
   return a + 1

In [12]:
printme(1)

2